Features/retrieve_last_ingested
bento-platform/gohan pull request #55
Opened 2023-09-29 19:06 UTC by noctillion

processing in VCF ingestion

2023-10-11 19:39 UTC, noctillion commented
This Pull Request include changes related to the retrieval of ingestion time for variants:

CreatedTime Metadata: With the updates in this PR, during the variant ingestion process, is captured and stored the CreatedTime for each variant. This metadata provides insights into when each variant was added.

Latest Created Field in Variants Overview: A new field named latest_created has been added to the variants overview. This field indicates the most recent creation timestamp among all variants.

Last Ingested File Information: For every dataset, we now include information about the last ingested file. These changes in the GetDatasetDataTypes function provide each dataset's most recent data updates.

2023-10-12 15:37 UTC, v-rocheleau requested changes
Error handling stuff, also should fix tests

2023-10-12 15:37 UTC, v-rocheleau commented on src/api/mvc/data-types/main.go
> +func GetReducedDataTypes(c echo.Context) error {
Can you add a comment describing what this function does? How is it different from GetDataTypes?

2023-10-12 15:42 UTC, v-rocheleau commented on src/api/repositories/elasticsearch/variants.go
> +							fmt.Printf("Error parsing 'createdTime' timestamp: %s\n", err)
The final return will also be an epoch zero timestamp

2023-11-14 21:36 UTC, v-rocheleau requested changes

2023-11-14 21:36 UTC, v-rocheleau commented on src/api/services/variants/main.go
> +	callProcessLatestCreated := func(key string, keyword string, _wg *sync.WaitGroup) {
Can you add comments in this function?

2023-11-20 19:11 UTC, v-rocheleau approved these changes

2023-11-20 19:11 UTC, merged